### ISSUE TITLE
How to run the code

### ISSUE THREAD

**Issue by fily1212** [liketheflower/YONOD#36]
Hi, 
I'm looking for a working method to perform object recognition in an indoor domain. 
I need to perform this object recognition in pictures extracted from AirBnB. I don't understand how to run the code. I'd like to use your model and the best checkpoint you have but for instance the file get_checkpoint.sh seems to give a different checkpoint of inference.sh. Can I ask you how to run? I have Windows 11 because CUDA is installed here, but if needed I can work on a Ubuntu installation.

**Comment by liketheflower** [comment]
Hi fily1212, thanks for submitting the issue here. What we did is:
1. We loaded a pretrained model based on COCO dataset.
2. Retrain the model based on SUN RGBD dataset: 1) RGB only. 2) DHS only (converted from depth image). 3) RGB DHS mixed images.

The step 2 needs generate a COCO similar dataset and also needs to update the label. We do have several checkpoints available. Let me upload the checkpoints to our github and you can see whether it works. In order to use this package, we need a new labels for the SUN RGBD dataset, which is also 80 categories.


Hope this helps. Also, for the hardware, we did the training and inference based on Ubuntu operating system with a TITAN GPU which has 8GB memory. Let me know if you have further questions.

**Comment by liketheflower** [comment]
Link to model checkpoints and configure files are added. Feel free to use those models.

**Comment by fily1212** [comment]
Hello, 
thank you for your quick response. I downloaded the model you uploaded on google drive (epoch50.pth). 
I tried to run something like this: 
`python tools/test.py  work_dirs/mask_rcnn_swin-t-p4-w7_fpn_ms-crop-3x_sunrgbd_rgb_dhs_mixed_with_chess1/mask_rcnn_swin-t-p4-w7_fpn_ms-crop-3x_sunrgbd_rgb_dhs_mixed_with_chess1.py my/epoch_50.pth --eval bbox segm`

But I have this error: 

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\yonod\lib\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "C:\ProgramData\Anaconda3\envs\yonod\lib\site-packages\mmdet\datasets\custom.py", line 97, in __init__
    self.data_infos = self.load_annotations(local_path)
  File "C:\ProgramData\Anaconda3\envs\yonod\lib\site-packages\mmdet\datasets\coco.py", line 72, in load_annotations
    self.coco = COCO(ann_file)
  File "C:\ProgramData\Anaconda3\envs\yonod\lib\site-packages\mmdet\datasets\api_wrappers\coco_api.py", line 23, in __init__
    super().__init__(annotation_file=annotation_file)
  File "C:\ProgramData\Anaconda3\envs\yonod\lib\site-packages\pycocotools\coco.py", line 81, in __init__
    with open(annotation_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/sophia/a/Xiaoke.Shen54/DATASET/sunrgbd_DO_NOT_DELETE/val/gts/raw_gts/det_val.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Progetti\yonod\y\tools\test.py", line 219, in <module>
    main()
  File "D:\Progetti\yonod\y\tools\test.py", line 162, in main
    dataset = build_dataset(cfg.data.test)
  File "C:\ProgramData\Anaconda3\envs\yonod\lib\site-packages\mmdet\datasets\builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "C:\ProgramData\Anaconda3\envs\yonod\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: CocoDataset: [Errno 2] No such file or directory: '/data/sophia/a/Xiaoke.Shen54/DATASET/sunrgbd_DO_NOT_DELETE/val/gts/raw_gts/det_val.json'

let's imagine that I need to perform object recognition on [this image](https://a0.muscache.com/im/pictures/dfa46fe6-755d-469d-a19d-e5df0fae802a.jpg?im_w=1440) (or more general in all the pics in a folder), in order to find chairs, tables or sofas. How do I have to launch the script? Do I need the det_val.json? How can I modify the config file in order to perform this obj recognition?

**Comment by liketheflower** [comment]
As the error shows, there is no file exist in your computer. "FileNotFoundError: CocoDataset: [Errno 2] No such file or directory: '/data/sophia/a/Xiaoke.Shen54/DATASET/sunrgbd_DO_NOT_DELETE/val/gts/raw_gts/det_val.json'" 

This is due to the code is testing the SUN RGBD dataset and you don't have the related file. If you want to test a specified image, please follow this [PR](https://github.com/liketheflower/mmdetection_beta/pull/3/) by using the customized mmdetection code. For that PR, basically, the input is a RGB dog image, and the output is detection result. You can update the cfg and checkpoint file to run the code.

You need the following customized code to do inference for each image. The following code is for the visualization and demo of the YONOD paper.
```bash
https://github.com/liketheflower/mmdetection_beta.git
```
